{
 "title": "A4 Supporting the Decision Process",
 "time": { "from": "2025-12-05T18:00:15.043Z", "to": "2025-12-05T19:10:57.901Z" },
 "panels": [
  {
   "title": "Bar Chart for Number of Requests",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time(num_requests[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Rate (10 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rate(num_requests[10m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peak Detection for Relevance",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time(index_relevance[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Random Load Moving (10m)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg_over_time(my_random[10m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Detecting Instability Spikes ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "stddev_over_time(num_requests[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Number of Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(num_requests[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Index Relevance (10 minutes)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(index_relevance[10m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}