{
 "title": "A3 Dashboard 1",
 "description": "Placeholder Description => TODO!!",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Total SMS Requests (Counter - Rate(10m))",
   "type": "timeseries",
   "description": "Total SMS classification requests (labels: endpoint)",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sms_requests_total{endpoint=\"metrics\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Model Predictions (Counter - Rate(10m))",
   "type": "timeseries",
   "description": "Total predictions made (labels: model_name, prediction, confidence_bucket)",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(model_predictions_total[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SMS Queue Size (Gauge)",
   "type": "gauge",
   "description": "Current messages in processing queue (labels: priority)",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sms_queue_size{priority=\"normal\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Loaded (Gauge)",
   "type": "gauge",
   "description": "Whether model is ready (1=yes, 0=no)",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_loaded", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SMS Classification Duration Max in Seconds (Histogram)",
   "type": "histogram",
   "description": "Time to classify SMS messages (labels: model_version)",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 10 },
   "targets": [
    { "expr": "0\n", "legendFormat": "__auto" },
    {
     "expr": "rate(sms_classification_duration_seconds_max{model_version=\"v1\"}[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Inference Time (Histogram - Average)",
   "type": "histogram",
   "description": "Model inference time (labels: model_name)",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by() (model_inference_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}