apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_dashboard: "1"
data:
  main-dashboard-a3.json: |
{{ .Files.Get "dashboards/main-dashboard-a3.json" | indent 4 }}
  decision-making-a4.json: |
{{ .Files.Get "dashboards/decision-making-a4.json" | indent 4 }}
  continuous-experimentation.json: |
{{ .Files.Get "dashboards/continuous-experimentation.json" | indent 4 }}