{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.app.name }}-gateway
spec:
  # Selector must match labels on the Istio ingress gateway pod
  # Default Istio installation uses label: istio=ingressgateway
  selector:
    istio: {{ .Values.istio.ingressGateway.selector }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.istio.host | quote }}
{{- end }}
