{{- if .Values.istio.enabled }}
# App DestinationRule
# Note: Sticky sessions are handled by VirtualService cookie matching, not consistentHash
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.app.name }}-destinationrule
spec:
  host: {{ .Values.app.name }}
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
---
# Model Service DestinationRule - ensures consistent routing (old-old, new-new)
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.model.name }}-destinationrule
spec:
  host: {{ .Values.model.name }}
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
{{- end }}
