{{- if .Values.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.model.name }}-monitor
  labels:
    app: {{ .Values.model.name }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.model.name }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.prometheus.scrapeInterval | default "15s" }}
      scrapeTimeout: {{ .Values.prometheus.scrapeTimeout | default "10s" }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}








