{{- if and .Values.istio.enabled .Values.istio.rateLimiting.enabled }}

apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: local-rate-limit
  namespace: {{ .Values.istio.ingressGateway.namespace }}
spec: 
# WorkLoadSelector uses a label to match the envoy proxies(pods) on which rate limit actions will apply.
  workloadSelector:
    labels: 
      istio: {{ .Values.istio.ingressGateway.selector }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener: 
          filterChain: 
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value: 
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              
      # applying user-based rate limiting

    - applyTo: HTTP_ROUTE
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            route:
              action: ANY

      patch:
        operation: MERGE
        # applying the rate limit rules
        value: 
          route:
            rate_limits:
              - actions: 
                  # user-based (this is the important part)
                  - request_headers:
                      header_name: "x-instance-id"
                      descriptor_key: "USER"

          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              stat_prefix: http_local_rate_limiter
              # if the user id matches only use that bucket, if not use the global bucket
              always_consume_default_token_bucket: false
              # token_bucket: This sections has 3 attributes
              token_bucket:
                # max_tokens: Specifies the maximum number of tokens in the bucket, 
                # representing the maximum allowed requests within a certain time frame.
                max_tokens: {{ .Values.istio.rateLimiting.burstSize }}
                # tokens_per_fill: Indicates the number of tokens added to the bucket with each fill, 
                # essentially the rate at which tokens are replenished.
                tokens_per_fill: {{ .Values.istio.rateLimiting.tokensPerFill }}
                # fill_interval: Defines the time interval at which the bucket is replenished with tokens.
                fill_interval: {{ .Values.istio.rateLimiting.fillIntervalSeconds }}s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add: 
                - append: false
                  header:
                    key: {{ quote .Values.istio.rateLimiting.headerName }}
                    value: {{ quote .Values.istio.rateLimiting.headerValue }}

              descriptors:
                - entries:
                    - key: "USER"
                      value: "001"
                  token_bucket:
                    fill_interval: 60s
                    max_tokens: 3
                    tokens_per_fill: 1
                - entries:
                    - key: "USER"
                      value: "002"
                  token_bucket:
                    fill_interval: 60s
                    max_tokens: 5
                    tokens_per_fill: 1
                - entries:
                    - key: "USER"
                      value: "003"
                  token_bucket:
                    fill_interval: 60s
                    max_tokens: 7
                    tokens_per_fill: 1

{{- end }}