{
 "title": "A3 Dashboard 1",
 "description": "Placeholder Description => TODO!!",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Number of Requests (Counter)",
   "type": "timeseries",
   "description": "number of requests to the web application",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "targets": [
    { "expr": "num_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Rate (Counter - Rate)",
   "type": "timeseries",
   "description": "converts data points into a range vector",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(num_requests[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Relevance (Gauge)",
   "type": "gauge",
   "description": "the percentage of requests that land on the index page",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "index_relevance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "My Random (Gauge - Avg over time)",
   "type": "gauge",
   "description": "Gauges can be accessed via a timeframe and then need an aggregator function\nfor the range vector. In this example, avg_over_time shows the average",
   "gridPos": { "h": 5, "w": 9, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(my_random[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Placeholder (Barchart)",
   "type": "barchart",
   "description": "waiting for the actual metric ",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 10 },
   "targets": [
    { "expr": "0", "legendFormat": "__auto" }
   ]
  }
 ]
}